{{- if .Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "app.dockerconfigSecretName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "1"
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | quote }}
{{- end }}
