apiVersion: v1
kind: Service
metadata:
  name: keda-add-ons-http-interceptor-proxy
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.platform.svc.cluster.local
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080