apiVersion: v1
kind: Service
metadata:
  name: keda-add-ons-http-interceptor-proxy-app
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.platform.svc.cluster.local
  ports:
    - port: 8080
      protocol: TCP