apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.fullname" . }}-post-install
  labels:
    app: hook-test
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: hook-test
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: post-install-job
        image: ghcr.io/neuro-inc/post-install-hook-kostia:latest
        command:
        - 'update-outputs'