{{- range .Values.PVCVolumes }}
{{- if .autocreate }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .pvcName }}
  labels:
    {{- include "llm-inference-app.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .accessMode }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end}}
  resources:
    requests:
      storage: {{ .storage }}
{{- end }}
{{- end }}
