{{- if .Values.autoscaling.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{.Values.autoscaling.basedOn}}-scaledobject
  namespace: "{{ .Release.Namespace }}"
spec:
  scaleTargetRef:
    name: {{ include "app.fullname" . }}
  maxReplicaCount:  {{ .Values.autoscaling.maxReplicas }}
  minReplicaCount:  {{ .Values.autoscaling.minReplicas }}
  triggers:
  {{- if eq .Values.autoscaling.basedOn "cpu" }}
  - type: cpu
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: "30"
  {{- else if eq .Values.autoscaling.basedOn "memory" }}
  - type: memory
    metricType: Utilization # Allowed types are 'Utilization' or 'AverageValue'
    metadata:
      value: "30"
  {{- else if eq .Values.autoscaling.basedOn "prometheus" }}
  - type: prometheus
    metadata:
      serverAddress: http://platform-prometheus-proxy:9090
      query: avg(rate(traefik_service_requests_total{code="200", exported_service="platform-jobs-job-6d1687f6-d012-4d6f-8cb0-606f82f8c75e-80@kubernetes"}[5m]))
      threshold: '1'
      activationThreshold: '1'
      namespace: platform
  {{- end }}

{{- end }}