kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: llm-httpscaledobject
  namespace: "{{ .Release.Namespace }}"
  annotations:
    httpscaledobject.keda.sh/skip-scaledobject-creation: "false"
spec:
    hosts:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
    scaleTargetRef:
        name: {{ include "app.fullname" . }}
        kind: Deployment
{{/*        apiVersion: apps/v1*/}}
        service: {{ include "app.fullname" . }}
        port: {{ .Values.service.port }}
    replicas:
        min: 0
        max: 2
    scaledownPeriod: 300
    scalingMetric: # requestRate and concurrency are mutually exclusive
        requestRate:
            granularity: 1s
            targetValue: 2
            window: 1m