apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-hook
  labels:
    app: hook-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  template:
    metadata:
      labels:
        app: hook-test
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-sa
      containers:
      - name: post-upgrade-hook
        image: ghcr.io/neuro-inc/post-install-hook-kostia:latest
        args:
        - "update-outputs"
        - "{{ .Values }}"
