gpuProvider: "amd"

image:
  repository: rocm/vllm-ci
  pullPolicy: IfNotPresent
  tag: v0.7.0

  # Provide at least an empty list so it’s not nil:
  imagePullSecrets: []

amdImage:
  repository: rocm/vllm-ci
  tag: 16366ee8bbdc30aad9776b74121cfc4d8f8c897d
  pullPolicy: IfNotPresent

nvidiaImage:
  repository: vllm/vllm-openai
  tag: v0.5.3.post1
  pullPolicy: IfNotPresent

env:
  HUGGING_FACE_HUB_TOKEN: ""

envAmd:
  HIP_VISIBLE_DEVICES: "0,1"
  TORCH_USE_HIP_DSA: "1"
  # etc.

envNvidia:
  NVIDIA_VISIBLE_DEVICES: "all"
  VLLM_USE_TRITON_FLASH_ATTN: "1"

llm:
  modelHFName: ""
  modelRevision: ""
  tokenizerHFName: ""
  tokenizerRevision: ""

model:
  modelHFName: ""
  modelRevision: ""
  tokenizerHFName: ""
  tokenizerRevision: ""

cache:
  enabled: true
  sizeLimit: 100Gi

service:
  port: 8000

ingress:
  enabled: false
  clusterName: ""

replicaCount: 1
healthChecksDelay: 60
resources: {}
serverExtraArgs: []

modelDownload:
  hookEnabled: false
  initEnabled: true
  image:
    repository: huggingface/downloader
    tag: 0.17.3
    pullPolicy: IfNotPresent
  resources: {}

tolerations:
  - key: platform.neuromation.io/job
    operator: Exists
    effect: NoSchedule
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  - key: amd.com/gpu
    operator: Exists
    effect: NoSchedule

