nameOverride: ""
fullnameOverride: ""

# Deployment
llm:
  modelHFName: ""
  tokenizerHFName: ""

replicaCount: 1

image:
  repository: vllm/vllm-openai
  pullPolicy: IfNotPresent
  tag: v0.3.3
  imagePullSecrets: []

resources: {}

healthChecksDelay: 5000

volumes:
  - pvcName: hf-cache
    managed: true
    accessMode: ReadWriteOnce
    storageClassName: ""
    storage: 300Gi
volumeMounts:
  - name: hf-cache
    mountPath: /root/.cache/huggingface
    readOnly: false

env:
  HUGGING_FACE_HUB_TOKEN: ""

podAnnotations: {}

nodeSelector: {}

tolerations:
  - key: platform.neuromation.io/job
    operator: Exists
    effect: NoSchedule
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

affinity: {}

priorityClassName: ""

# Service
service:
  port: 8000

# Ingress
ingress:
  enabled: false
  className: traefik
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
