# This is mostly show-off example of config adjustments

llm:
  modelHFName: lmsys/vicuna-7b-v1.3
  tokenizerHFName: lmsys/vicuna-7b-v1.3

serverExtraArgs:
  - --dtype=half

ingress:
  enabled: true
  clusterName: scottdc

preset_name: H100x1
